version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
